version: '3.8'

services:
  redis:
    image: redis:7.0
    volumes:
      - .:/code

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: notifico
    volumes:
      - postgres:/var/lib/postgresql/data
      - .:/code

  frontend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    environment:
      FLASK_DEBUG: 1
      NOTIFICO_DB: postgresql://postgres:notifico@db/postgres
    command: poetry run notifico run --host 0.0.0.0

volumes:
  postgres: