version: "3.9"
services:
  # We build the base image just once, then depend on it in the workers and
  # frontend. Prevents docker-compose from being stupid and rebuilding "."
  # multiple times.
  build:
    image: notifico_base_image
    build:
      context: .

  redis:
    image: "redis:alpine"

  app:
    image: notifico_base_image
    depends_on: [build, redis]

    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: "development"
      NOTI_REDIS: "redis://redis:6379/0"

    working_dir: /app
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        python setup.py develop
        notifico run --reload

  worker:
    image: notifico_base_image
    depends_on: [build, redis]

    volumes:
      - .:/app
    environment:
      FLASK_ENV: "development"
      NOTI_REDIS: "redis://redis:6379/0"

    working_dir: /app
    entrypoint: ["celery", "-A", "notifico.tasks.celery", "worker"]
