version: "3.9"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: "development"
      NOTIFICO_CONFIG: "/app/misc/docker_config.py"
  redis:
    image: "redis:alpine"
