"""Testing 123

Revision ID: 35460903d8bf
Revises: None
Create Date: 2012-11-25 16:39:33.562323

"""

# revision identifiers, used by Alembic.
revision = '35460903d8bf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hook', sa.Column('config', sa.PickleType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hook', 'config')
    ### end Alembic commands ###
