"""empty message

Revision ID: 1b901dcc660f
Revises: cad59c3d601a
Create Date: 2022-10-23 23:28:28.725563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b901dcc660f'
down_revision = 'cad59c3d601a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('role',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('permission_association',
    sa.Column('role_id', sa.String(length=255), nullable=True),
    sa.Column('permission_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.name'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.name'], )
    )
    op.create_table('role_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_column('user', 'company')
    op.drop_column('user', 'website')
    op.drop_column('user', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('role_association')
    op.drop_table('permission_association')
    op.drop_table('role')
    op.drop_table('permission')
    # ### end Alembic commands ###
