"""empty message

Revision ID: 4250727b1899
Revises: b4a63bed6b7f
Create Date: 2023-04-07 05:41:48.068814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4250727b1899'
down_revision = 'b4a63bed6b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_count', sa.BigInteger(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('sender', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['chat_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_id_and_ts', 'chat_message', [sa.text('timestamp DESC'), 'log_id'], unique=False)
    op.add_column('channel', sa.Column('log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'channel', 'chat_log', ['log_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channel', type_='foreignkey')
    op.drop_column('channel', 'log_id')
    op.drop_index('idx_log_id_and_ts', table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_table('chat_log')
    # ### end Alembic commands ###
