"""empty message

Revision ID: a24f38bb188b
Revises: 1b901dcc660f
Create Date: 2022-10-24 17:33:53.523008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24f38bb188b'
down_revision = '1b901dcc660f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_full_name_key', 'project', type_='unique')
    op.drop_column('project', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('full_name', sa.VARCHAR(length=101), autoincrement=False, nullable=False))
    op.create_unique_constraint('project_full_name_key', 'project', ['full_name'])
    # ### end Alembic commands ###
