"""empty messagmodele

Revision ID: a50852b553b1
Revises: 
Create Date: 2022-10-07 06:34:35.831209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a50852b553b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_event')
    op.drop_index('sqlite_autoindex_group_1', table_name='group')
    op.create_unique_constraint(None, 'group', ['name'])
    op.drop_index('sqlite_autoindex_project_1', table_name='project')
    op.create_unique_constraint(None, 'project', ['full_name'])
    op.drop_index('sqlite_autoindex_user_1', table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('sqlite_autoindex_user_1', 'user', ['username'], unique=False)
    op.drop_constraint(None, 'project', type_='unique')
    op.create_index('sqlite_autoindex_project_1', 'project', ['full_name'], unique=False)
    op.drop_constraint(None, 'group', type_='unique')
    op.create_index('sqlite_autoindex_group_1', 'group', ['name'], unique=False)
    op.create_table('bot_event',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('channel', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('host', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('port', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ssl', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('event', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bot_event_pkey')
    )
    # ### end Alembic commands ###
