"""empty message

Revision ID: b4a63bed6b7f
Revises: 75770b11c67a
Create Date: 2022-11-07 10:45:50.258806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a63bed6b7f'
down_revision = '75770b11c67a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('password', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'password')
    # ### end Alembic commands ###
