"""empty message

Revision ID: ebe78b1ff4dc
Revises: 4250727b1899
Create Date: 2023-04-07 05:59:17.690718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe78b1ff4dc'
down_revision = '4250727b1899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('logged', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'logged')
    # ### end Alembic commands ###
