---
name: 'deploy'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: 'master'
          git_remote_url: 'ssh://dokku@montreal.tkte.ch:22/notifico'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}